package model;

// default package
// Generated 12 janv. 2012 17:41:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Domain generated by hbm2java
 */
@Entity
@Table(name = "domain", schema = "public")
public class Domain implements java.io.Serializable, ModelInterface {

	private int idDomain;
	private String name;
	private Set<TableDeFait> tableDeFaits = new HashSet<TableDeFait>(0);

	public Domain() {
	}

	public Domain(int idDomain) {
		this.idDomain = idDomain;
	}

	public Domain(int idDomain, String name, Set<TableDeFait> tableDeFaits) {
		this.idDomain = idDomain;
		this.name = name;
		this.tableDeFaits = tableDeFaits;
	}

	@Id
	@Column(name = "id_domain", unique = true, nullable = false)
	public int getIdDomain() {
		return this.idDomain;
	}

	public void setIdDomain(int idDomain) {
		this.idDomain = idDomain;
	}

	@Column(name = "name", length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "domain")
	public Set<TableDeFait> getTableDeFaits() {
		return this.tableDeFaits;
	}

	public void setTableDeFaits(Set<TableDeFait> tableDeFaits) {
		this.tableDeFaits = tableDeFaits;
	}

}
