package src.model;

// default package
// Generated 12 janv. 2012 10:38:09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * EntryInformation generated by hbm2java
 */
@Entity
@Table(name = "entry_information", schema = "public")
public class EntryInformation implements java.io.Serializable {

	private int idEntry;
	private String entryName;
	private TableDeFait tableDeFait;

	public EntryInformation() {
	}

	public EntryInformation(int idEntry) {
		this.idEntry = idEntry;
	}

	public EntryInformation(int idEntry, String entryName,
			TableDeFait tableDeFait) {
		this.idEntry = idEntry;
		this.entryName = entryName;
		this.tableDeFait = tableDeFait;
	}

	@Id
	@Column(name = "id_entry", unique = true, nullable = false)
	public int getIdEntry() {
		return this.idEntry;
	}

	public void setIdEntry(int idEntry) {
		this.idEntry = idEntry;
	}

	@Column(name = "entry_name", length = 50)
	public String getEntryName() {
		return this.entryName;
	}

	public void setEntryName(String entryName) {
		this.entryName = entryName;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "entryInformation")
	public TableDeFait getTableDeFait() {
		return this.tableDeFait;
	}

	public void setTableDeFait(TableDeFait tableDeFait) {
		this.tableDeFait = tableDeFait;
	}

}
