package src.model;

// default package
// Generated 12 janv. 2012 10:38:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Function generated by hbm2java
 */
@Entity
@Table(name = "function", schema = "public")
public class Function implements java.io.Serializable {

	private int idFunction;
	private String function;
	private String catalyticActivity;
	private Set<TableDeFait> tableDeFaits = new HashSet<TableDeFait>(0);

	public Function() {
	}

	public Function(int idFunction) {
		this.idFunction = idFunction;
	}

	public Function(int idFunction, String function, String catalyticActivity,
			Set<TableDeFait> tableDeFaits) {
		this.idFunction = idFunction;
		this.function = function;
		this.catalyticActivity = catalyticActivity;
		this.tableDeFaits = tableDeFaits;
	}

	@Id
	@Column(name = "id_function", unique = true, nullable = false)
	public int getIdFunction() {
		return this.idFunction;
	}

	public void setIdFunction(int idFunction) {
		this.idFunction = idFunction;
	}

	@Column(name = "function", length = 25)
	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	@Column(name = "catalytic_activity", length = 25)
	public String getCatalyticActivity() {
		return this.catalyticActivity;
	}

	public void setCatalyticActivity(String catalyticActivity) {
		this.catalyticActivity = catalyticActivity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "function")
	public Set<TableDeFait> getTableDeFaits() {
		return this.tableDeFaits;
	}

	public void setTableDeFaits(Set<TableDeFait> tableDeFaits) {
		this.tableDeFaits = tableDeFaits;
	}

}
