package model;

// default package
// Generated 13 janv. 2012 16:20:29 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GeneralAnnotation generated by hbm2java
 */
@Entity
@Table(name = "general_annotation", schema = "public")
public class GeneralAnnotation implements java.io.Serializable, ModelInterface {

	private int idGeneralAnnotation;
	private String pathway;
	private String tissueSpecificity;
	private String subscellularLocation;
	private String biophysicochemicalPriopoerties;
	private Set<TableDeFait> tableDeFaits = new HashSet<TableDeFait>(0);

	public GeneralAnnotation() {
	}

	public GeneralAnnotation(int idGeneralAnnotation) {
		this.idGeneralAnnotation = idGeneralAnnotation;
	}

	public GeneralAnnotation(int idGeneralAnnotation, String pathway,
			String tissueSpecificity, String subscellularLocation,
			String biophysicochemicalPriopoerties, Set<TableDeFait> tableDeFaits) {
		this.idGeneralAnnotation = idGeneralAnnotation;
		this.pathway = pathway;
		this.tissueSpecificity = tissueSpecificity;
		this.subscellularLocation = subscellularLocation;
		this.biophysicochemicalPriopoerties = biophysicochemicalPriopoerties;
		this.tableDeFaits = tableDeFaits;
	}

	@Id
	@Column(name = "id_general_annotation", unique = true, nullable = false)
	public int getIdGeneralAnnotation() {
		return this.idGeneralAnnotation;
	}

	public void setIdGeneralAnnotation(int idGeneralAnnotation) {
		this.idGeneralAnnotation = idGeneralAnnotation;
	}

	@Column(name = "pathway", length = 25)
	public String getPathway() {
		return this.pathway;
	}

	public void setPathway(String pathway) {
		this.pathway = pathway;
	}

	@Column(name = "tissue_specificity", length = 25)
	public String getTissueSpecificity() {
		return this.tissueSpecificity;
	}

	public void setTissueSpecificity(String tissueSpecificity) {
		this.tissueSpecificity = tissueSpecificity;
	}

	@Column(name = "subscellular_location", length = 25)
	public String getSubscellularLocation() {
		return this.subscellularLocation;
	}

	public void setSubscellularLocation(String subscellularLocation) {
		this.subscellularLocation = subscellularLocation;
	}

	@Column(name = "biophysicochemical_priopoerties", length = 25)
	public String getBiophysicochemicalPriopoerties() {
		return this.biophysicochemicalPriopoerties;
	}

	public void setBiophysicochemicalPriopoerties(
			String biophysicochemicalPriopoerties) {
		this.biophysicochemicalPriopoerties = biophysicochemicalPriopoerties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "generalAnnotation")
	public Set<TableDeFait> getTableDeFaits() {
		return this.tableDeFaits;
	}

	public void setTableDeFaits(Set<TableDeFait> tableDeFaits) {
		this.tableDeFaits = tableDeFaits;
	}

}
