package model;

// default package
// Generated 12 janv. 2012 17:41:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SequenceAnnotation generated by hbm2java
 */
@Entity
@Table(name = "sequence_annotation", schema = "public")
public class SequenceAnnotation implements java.io.Serializable, ModelInterface {

	private int idSeqAnnotation;
	private Short turn;
	private Short helix;
	private Short site;
	private Short transmembrane;
	private Short intermembrane;
	private Short chain;
	private Short betaStrand;
	private Set<TableDeFait> tableDeFaits = new HashSet<TableDeFait>(0);

	public SequenceAnnotation() {
	}

	public SequenceAnnotation(int idSeqAnnotation) {
		this.idSeqAnnotation = idSeqAnnotation;
	}

	public SequenceAnnotation(int idSeqAnnotation, Short turn, Short helix,
			Short site, Short transmembrane, Short intermembrane, Short chain,
			Short betaStrand, Set<TableDeFait> tableDeFaits) {
		this.idSeqAnnotation = idSeqAnnotation;
		this.turn = turn;
		this.helix = helix;
		this.site = site;
		this.transmembrane = transmembrane;
		this.intermembrane = intermembrane;
		this.chain = chain;
		this.betaStrand = betaStrand;
		this.tableDeFaits = tableDeFaits;
	}

	@Id
	@Column(name = "id_seq_annotation", unique = true, nullable = false)
	public int getIdSeqAnnotation() {
		return this.idSeqAnnotation;
	}

	public void setIdSeqAnnotation(int idSeqAnnotation) {
		this.idSeqAnnotation = idSeqAnnotation;
	}

	@Column(name = "turn")
	public Short getTurn() {
		return this.turn;
	}

	public void setTurn(Short turn) {
		this.turn = turn;
	}

	@Column(name = "helix")
	public Short getHelix() {
		return this.helix;
	}

	public void setHelix(Short helix) {
		this.helix = helix;
	}

	@Column(name = "site")
	public Short getSite() {
		return this.site;
	}

	public void setSite(Short site) {
		this.site = site;
	}

	@Column(name = "transmembrane")
	public Short getTransmembrane() {
		return this.transmembrane;
	}

	public void setTransmembrane(Short transmembrane) {
		this.transmembrane = transmembrane;
	}

	@Column(name = "intermembrane")
	public Short getIntermembrane() {
		return this.intermembrane;
	}

	public void setIntermembrane(Short intermembrane) {
		this.intermembrane = intermembrane;
	}

	@Column(name = "chain")
	public Short getChain() {
		return this.chain;
	}

	public void setChain(Short chain) {
		this.chain = chain;
	}

	@Column(name = "beta_strand")
	public Short getBetaStrand() {
		return this.betaStrand;
	}

	public void setBetaStrand(Short betaStrand) {
		this.betaStrand = betaStrand;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sequenceAnnotation")
	public Set<TableDeFait> getTableDeFaits() {
		return this.tableDeFaits;
	}

	public void setTableDeFaits(Set<TableDeFait> tableDeFaits) {
		this.tableDeFaits = tableDeFaits;
	}

}
